apiVersion: v1
kind: Pod
metadata:
  name: simple2
  labels:
    app: myapp
    type: front-end
spec:
  nodeName: master
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80