apiVersion: v1
kind: Pod
metadata:
  name: simple2
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "800Mi"
          cpu: "800m"
        requests:
          memory: "600Mi"
          cpu: "400m"
  nodeSelector:
    size: Large
